//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAGINAINVENTARIO.MODELO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARTICULOS
    {
        public ARTICULOS()
        {
            this.COTIZACIONES = new HashSet<COTIZACIONES>();
            this.DETALLEFACTURAS = new HashSet<DETALLEFACTURAS>();
        }
    
        public int id_articulo { get; set; }
        public string Articulo { get; set; }
        public string Cantidad { get; set; }
        public int Precio { get; set; }
    
        public virtual ICollection<COTIZACIONES> COTIZACIONES { get; set; }
        public virtual ICollection<DETALLEFACTURAS> DETALLEFACTURAS { get; set; }
    }
}
