//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAGINAINVENTARIO.MODELO
{
    using System;
    using System.Collections.Generic;
    
    public partial class COTIZACIONES
    {
        public int id_Cotizacion { get; set; }
        public int Id_articulos { get; set; }
        public int Monto { get; set; }
        public int Cantidad { get; set; }
        public int Id_cliente { get; set; }
    
        public virtual ARTICULOS ARTICULOS { get; set; }
        public virtual CLIENTES CLIENTES { get; set; }
    }
}
