//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAGINAINVENTARIO.MODELO
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURAS
    {
        public int Id_factura { get; set; }
        public int id_detalle { get; set; }
        public int Id_estado { get; set; }
        public int Id_tipo { get; set; }
        public Nullable<int> Id_usuario { get; set; }
    
        public virtual DETALLEFACTURAS DETALLEFACTURAS { get; set; }
        public virtual ESTADOSFACTURAS ESTADOSFACTURAS { get; set; }
        public virtual TIPOSDEFACTURAS TIPOSDEFACTURAS { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
