//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAGINAINVENTARIO.MODELO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class INVENTARIODBEntities : DbContext
    {
        public INVENTARIODBEntities()
            : base("name=INVENTARIODBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ARTICULOS> ARTICULOS { get; set; }
        public DbSet<CLIENTES> CLIENTES { get; set; }
        public DbSet<COTIZACIONES> COTIZACIONES { get; set; }
        public DbSet<DETALLEFACTURAS> DETALLEFACTURAS { get; set; }
        public DbSet<ESTADOSFACTURAS> ESTADOSFACTURAS { get; set; }
        public DbSet<FACTURAS> FACTURAS { get; set; }
        public DbSet<TIPOSDEFACTURAS> TIPOSDEFACTURAS { get; set; }
        public DbSet<TIPOSDEUSUARIOS> TIPOSDEUSUARIOS { get; set; }
        public DbSet<USUARIOS> USUARIOS { get; set; }
        public DbSet<Factura_View> Factura_View { get; set; }
    }
}
