//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAGINAINVENTARIO.MODELO
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        public USUARIOS()
        {
            this.FACTURAS = new HashSet<FACTURAS>();
        }
    
        public int Id_usuario { get; set; }
        public string Usuario { get; set; }
        public string Contraseña { get; set; }
        public int Id_tipoU { get; set; }
    
        public virtual ICollection<FACTURAS> FACTURAS { get; set; }
        public virtual TIPOSDEUSUARIOS TIPOSDEUSUARIOS { get; set; }
    }
}
