<%@ Page Title="" Language="C#" MasterPageFile="~/FORMULARIO/PaginaMaestra.Master" AutoEventWireup="true" CodeBehind="Factura.aspx.cs" Inherits="PAGINAINVENTARIO.FORMULARIO.Factura" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentTitle" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="head" runat="server">
    <style type="text/css">
        .auto-style1 {
            width: 214px;
        }
    </style>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentBody" runat="server">
        
        <asp:SqlDataSource ID="ArticuloSource" runat="server" ConnectionString="<%$ ConnectionStrings:INVENTARIODBConnectionString %>" SelectCommand="SELECT * FROM [ARTICULOS]"></asp:SqlDataSource>
        
        
        <asp:SqlDataSource ID="ClienteSource" runat="server" ConnectionString="<%$ ConnectionStrings:INVENTARIODBConnectionString %>" SelectCommand="SELECT * FROM [CLIENTES]"></asp:SqlDataSource>
        
    
    <table class="nav-justified">
        <tr>
            <td class="auto-style1"><asp:Label ID="Label6" runat="server" Text="Articulo"></asp:Label></td>
            <td><asp:DropDownList ID="ddArticulo" runat="server" DataSourceID="ArticuloSource" DataTextField="Articulo" DataValueField="id_articulo" CssClass="dropdown"></asp:DropDownList></td>
        </tr>
        <tr>
            <td class="auto-style1"><asp:Label ID="Label1" runat="server" Text="Monto"></asp:Label></td>
            <td><asp:TextBox ID="txtMonto" runat="server" CssClass="form-inline"></asp:TextBox></td>
        </tr>
        <tr>
            <td class="auto-style1"><asp:Label ID="Label2" runat="server" Text="Cantidad"></asp:Label></td>
            <td><asp:TextBox ID="txtCantidad" runat="server" CssClass="form-inline"></asp:TextBox></td>
        </tr>
        <tr>
            <td class="auto-style1"><asp:Label ID="Label3" runat="server" Text="Cliente"></asp:Label></td>
            <td> <asp:DropDownList ID="ddCliente" runat="server" DataSourceID="ClienteSource" DataTextField="Nombre" DataValueField="Id_cliente" CssClass="dropdown"></asp:DropDownList></td>
        </tr>
        <tr>
            <td class="auto-style1"><asp:Label ID="Label4" runat="server" Text="Descuento"></asp:Label></td>
            <td><asp:TextBox ID="txtDescuento" runat="server" CssClass="form-inline"></asp:TextBox></td>
            
        </tr>
        <tr>
            <td class="auto-style1"><asp:Button ID="Button1" runat="server" Text="FACTURAR" CssClass="btn btn-default" OnClick="btnGuardar_Click" /></td>
            <td><asp:Button ID="btnAgregar" runat="server" Text="LIMPIAR"  CssClass="btn btn-default" OnClick="btnAgregar_Click"/></td>
        </tr>
    </table>
    <br />
    <div id="tablaFactura">
        <asp:GridView ID="gvFactura" runat="server" AllowPaging="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="id_detalle" DataSourceID="FacturaSource" PageIndex="5" CssClass="table-condensed" PageSize="5">
            <Columns>
                <asp:BoundField DataField="id_detalle" HeaderText="id_detalle" InsertVisible="False" ReadOnly="True" SortExpression="id_detalle" />
                <asp:BoundField DataField="Id_articulos" HeaderText="Articulos" SortExpression="Id_articulos" />
                <asp:BoundField DataField="Monto" HeaderText="Monto" SortExpression="Monto" />
                <asp:BoundField DataField="Cantidad" HeaderText="Cantidad" SortExpression="Cantidad" />
                <asp:BoundField DataField="Id_cliente" HeaderText="Cliente" SortExpression="Id_cliente" />
                <asp:BoundField DataField="Descuento" HeaderText="Descuento" SortExpression="Descuento" />
            </Columns>
        </asp:GridView>

        <asp:SqlDataSource ID="FacturaSource" runat="server" ConnectionString="<%$ ConnectionStrings:INVENTARIODBConnectionString %>" SelectCommand="SELECT * FROM [DETALLEFACTURAS]" UpdateCommand="UPDATE[DETALLEFACTURAS] SET [Monto]=@Monto,[Cantidad]=@Cantidad,[Descuento]=@Descuento WHERE [id_detalle]=@id_detalle" DeleteCommand="DELETE FROM [DETALLEFACTURAS] WHERE [id_detalle]=@id_detalle"></asp:SqlDataSource>
        
    </div>
   
</asp:Content>
