<%@ Page Title="" Language="C#" MasterPageFile="~/FORMULARIO/PaginaMaestra.Master" AutoEventWireup="true" CodeBehind="Factura.aspx.cs" Inherits="PAGINAINVENTARIO.FORMULARIO.Factura" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentTitle" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="head" runat="server">
    <style type="text/css">
        .auto-style1 {
            width: 214px;
        }
    </style>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentBody" runat="server">
        
        <asp:SqlDataSource ID="ArticuloSource" runat="server" ConnectionString="<%$ ConnectionStrings:INVENTARIODBConnectionString %>" SelectCommand="SELECT * FROM [ARTICULOS]"></asp:SqlDataSource>
        
        
        <asp:SqlDataSource ID="ClienteSource" runat="server" ConnectionString="<%$ ConnectionStrings:INVENTARIODBConnectionString %>" SelectCommand="SELECT * FROM [CLIENTES]"></asp:SqlDataSource>
        
    
    <table class="nav-justified">
        <tr>
            <td class="auto-style1"><asp:Label ID="Label6" runat="server" Text="Articulo"></asp:Label></td>
            <td><asp:DropDownList ID="ddArticulo" runat="server" DataSourceID="ArticuloSource" DataTextField="Articulo" DataValueField="id_articulo" CssClass="dropdown"></asp:DropDownList></td>
        </tr>
        <tr>
            <td class="auto-style1"><asp:Label ID="Label1" runat="server" Text="Monto"></asp:Label></td>
            <td><asp:TextBox ID="txtMonto" runat="server" CssClass="form-inline"></asp:TextBox></td>
        </tr>
        <tr>
            <td class="auto-style1"><asp:Label ID="Label2" runat="server" Text="Cantidad"></asp:Label></td>
            <td><asp:TextBox ID="txtCantidad" runat="server" CssClass="form-inline"></asp:TextBox></td>
        </tr>
        <tr>
            <td class="auto-style1"><asp:Label ID="Label3" runat="server" Text="Cliente"></asp:Label></td>
            <td> <asp:DropDownList ID="ddCliente" runat="server" DataSourceID="ClienteSource" DataTextField="Nombre" DataValueField="Id_cliente" CssClass="dropdown"></asp:DropDownList></td>
        </tr>
        <tr>
            <td class="auto-style1"><asp:Label ID="Label4" runat="server" Text="Descuento"></asp:Label></td>
            <td><asp:TextBox ID="txtDescuento" runat="server" CssClass="form-inline"></asp:TextBox></td>
            
        </tr>
        <tr>
            <td class="auto-style1"><asp:Button ID="Button1" runat="server" Text="FACTURAR" CssClass="btn btn-default" OnClick="btnGuardar_Click" /></td>
            <td><asp:Button ID="Button2" runat="server" Text="AGREGAR"  CssClass="btn btn-default" OnClick="btnAgregar_Click"/></td>
        </tr>
    </table>
    <br />
    <div id="tablaFactura">
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AllowPaging="True" PageIndex="10" CssClass="table-condensed">
            <Columns>
                <asp:BoundField DataField="IdArticulo" HeaderText="Articulo" />
                <asp:BoundField DataField="IdMonto" HeaderText="Monto" />
                <asp:BoundField DataField="IdCantidad" HeaderText="Cantidad" />
                <asp:BoundField DataField="IdCliente" HeaderText="Cliente" />
                <asp:BoundField DataField="IdDescuento" HeaderText="Descuento" />
            </Columns>
        </asp:GridView>
        <asp:SqlDataSource ID="DetalleSource" runat="server" ConnectionString="<%$ ConnectionStrings:INVENTARIODBConnectionString %>" SelectCommand="SELECT * FROM [DETALLEFACTURAS]"></asp:SqlDataSource>
    </div>
   
</asp:Content>
