<%@ Page Title="" Language="C#" MasterPageFile="~/FORMULARIO/PaginaMaestra.Master" AutoEventWireup="true" CodeBehind="Factura.aspx.cs" Inherits="PAGINAINVENTARIO.FORMULARIO.Factura" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentTitle" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentBody" runat="server">
    <div id="tablaFactura">
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AllowPaging="True" PageIndex="10" CssClass="table-condensed">
            <Columns>
                <asp:BoundField HeaderText="Articulo" />
                <asp:BoundField HeaderText="Monto" />
                <asp:BoundField HeaderText="Cantidad" />
                <asp:BoundField HeaderText="Cliente" />
                <asp:BoundField HeaderText="Descuento" />
            </Columns>
        </asp:GridView>
        <asp:SqlDataSource ID="DetalleSource" runat="server" ConnectionString="<%$ ConnectionStrings:INVENTARIODBConnectionString %>" SelectCommand="SELECT * FROM [DETALLEFACTURAS]"></asp:SqlDataSource>
    </div>
    <div id="formularioFactura" class="form-group">
        <asp:Label ID="Label1" runat="server" Text="Articulo"></asp:Label>
        <asp:DropDownList ID="ddArticulo" runat="server" DataSourceID="ArticuloSource" DataTextField="Articulo" DataValueField="id_articulo" CssClass="dropdown"></asp:DropDownList>
        <asp:SqlDataSource ID="ArticuloSource" runat="server" ConnectionString="<%$ ConnectionStrings:INVENTARIODBConnectionString %>" SelectCommand="SELECT * FROM [ARTICULOS]"></asp:SqlDataSource>
        <br />
        <br />
        <asp:Label ID="Label2" runat="server" Text="Monto"></asp:Label>
        <asp:TextBox ID="txtMonto" runat="server" CssClass="form-inline"></asp:TextBox>
        <br />
        <br />
        <asp:Label ID="Label3" runat="server" Text="Cantidad"></asp:Label>
        <asp:TextBox ID="txtCantidad" runat="server" CssClass="form-inline"></asp:TextBox>
        <br />
        <br />
        <asp:Label ID="Label4" runat="server" Text="Cliente"></asp:Label>
        <asp:DropDownList ID="ddCliente" runat="server" DataSourceID="ClienteSource" DataTextField="Nombre" DataValueField="Id_cliente" CssClass="dropdown"></asp:DropDownList>
        <asp:SqlDataSource ID="ClienteSource" runat="server" ConnectionString="<%$ ConnectionStrings:INVENTARIODBConnectionString %>" SelectCommand="SELECT * FROM [CLIENTES]"></asp:SqlDataSource>
        <br />
        <br />
        <asp:Label ID="Label5" runat="server" Text="Descuento"></asp:Label>
        <asp:TextBox ID="txtDescuento" runat="server" CssClass="form-inline"></asp:TextBox>
        <br />
        <br />
        <br />
        <asp:Button ID="btnGuardar" runat="server" Text="FACTURAR" CssClass="btn btn-default" OnClick="btnGuardar_Click" />
        <asp:Button ID="btnAgregar" runat="server" Text="AGREGAR"  CssClass="btn btn-default" OnClick="btnAgregar_Click"/>
    </div>
</asp:Content>
