<%@ Page Title="" Language="C#" MasterPageFile="~/FORMULARIO/PaginaMaestra.Master" AutoEventWireup="true" CodeBehind="ListadoClientes.aspx.cs" Inherits="PAGINAINVENTARIO.FORMULARIO.ListadoClientes" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentTitle" runat="server">
    LISTADO
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="head" runat="server">
    <link href="../Content/EstiloPersonalizado.css" rel="stylesheet" />
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentBody" runat="server">

    <div id="table" class="display">

      <asp:GridView ID="gvListado" runat="server" CssClass="table-condensed"  AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateColumns="False" DataSourceID="SqlDataSource1" DataKeyNames="Id_cliente" AllowPaging="True" PageIndex="10">
            <Columns>
                <asp:BoundField DataField="Id_cliente" HeaderText="Id_cliente" InsertVisible="False" ReadOnly="True" SortExpression="Id_cliente" />
                <asp:BoundField DataField="Nombre" HeaderText="Nombre" SortExpression="Nombre" />
                <asp:BoundField DataField="Direccion" HeaderText="Direccion" SortExpression="Direccion" />
                
            </Columns>
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:INVENTARIODBConnectionString %>" SelectCommand="SELECT [Nombre], [Direccion], [Id_cliente] FROM [CLIENTES]" UpdateCommand="UPDATE [CLIENTES] SET [Nombre] = @Nombre, [Direccion] = @Direccion WHERE [Id_cliente] = @Id_cliente" DeleteCommand="DELETE FROM [CLIENTES] WHERE [Id_cliente] = @Id_cliente" InsertCommand="INSERT INTO [CLIENTES] ([Nombre], [Direccion]) VALUES (@Nombre, @Direccion)">
            <DeleteParameters>
                <asp:Parameter Name="Id_cliente" Type="Int32" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="Nombre" Type="String" />
                <asp:Parameter Name="Direccion" Type="String" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="Nombre" Type="String" />
                <asp:Parameter Name="Direccion" Type="String" />
                <asp:Parameter Name="Id_cliente" Type="Int32" />
            </UpdateParameters>
        </asp:SqlDataSource>
    </div>
    <div id="formularioCliente">
        <asp:Label ID="Label1" runat="server" Text="Nombre"></asp:Label> <br />
        <asp:TextBox ID="txtNombre" runat="server"></asp:TextBox><br />
        <asp:Label ID="Label2" runat="server" Text="Direccion"></asp:Label><br />
        <asp:TextBox ID="txtDireccion" runat="server"></asp:TextBox><br /> <br />
        <asp:Button ID="btnGuardar" runat="server" Text="Guardar" CssClass="btn btn-default" OnClick="btnGuardar_Click" />
    </div>
</asp:Content>
